### ISSUE TITLE
[Feature] - refactor miranum docu landing page

### ISSUE THREAD

**Issue by rami-nk** [Miragon/miranum-docs#65]
- [x] Description created
- [x] Reviewed by peer: @rami-nk 
- [x] Prioritised

# Description

We recognized that our Miranum documentation's landing page wasn't quite hitting the mark. It lacked an engaging introduction and didn't visually appeal to our users. Furthermore, it fell short in highlighting the core features of Miranum, an integral blend of Miranum-IDE and Miranum-Connect.
In order to rectify this, we've decided to breathe new life into it. We're in the process of giving our landing page a modern, fresh, and intuitive design overhaul that will not only enhance its aesthetics but also improve its navigability.
Our goal is to showcase Miranum's unique strengths and capabilities, spotlighting the synergy of Miranum-IDE and Miranum-Connect, so that users can easily understand and appreciate the value these tools bring to their projects. 

## Sub-Tasks
 
```[tasklist]
### Tasks
- [ ] <your-issue-here>
```

**Comment by DaAnda97** [comment]
Could you point out miranum platform as well please?

**Comment by rami-nk** [comment]
> Could you point out miranum platform as well please?

What exactly do you want to be pointed out? As a new section on the landing page?

**Comment by Hafflgav** [comment]
> Could you point out miranum platform as well please?

@DaAnda97, I am rather reluctant to add miranum-platform to the landing page just yet, as the project is still private. 
Do you have a guess when it will be released to the public?

**Comment by rami-nk** [comment]
> 

That is actually a very good and valid point!
